#!/usr/bin/env bash
set -euo pipefail
fail(){ echo "FAIL: $1" >&2; exit 1; }
UI="app/src/main/java/com/saney/ytmimporter/ui/UiChrome.kt"
SRC="app/src/main/java/com/saney/ytmimporter"
test -f "$UI" || fail "UiChrome.kt missing"
grep -A55 'fun configureWindow()' "$UI" | grep -q 'setWindowAnimations(0)' || fail "Window animation still enabled"
grep -A20 'val holder =' "$UI" | grep -q 'Gravity.TOP' || fail "dialog not TOP anchored"
grep -q 'fun hideDecor()' "$UI" || fail "whole-decor hide guard missing"
grep -q 'stablePreDraws' "$UI" || fail "stable pre-draw counter missing"
grep -q 'lastGeometry' "$UI" || fail "stable geometry signature missing"
grep -q 'revealAfterStableGeometry' "$UI" || fail "stable reveal helper missing"
SHOW_LINE="$(grep -n '^[[:space:]]*dialog.show()$' "$UI" | tail -n 1 | cut -d: -f1)"
PRE_CONFIG_LINE="$(grep -n '^[[:space:]]*configureWindow()$' "$UI" | head -n 1 | cut -d: -f1)"
POST_CONFIG_LINE="$(grep -n '^[[:space:]]*configureWindow()$' "$UI" | tail -n 1 | cut -d: -f1)"
[ "$PRE_CONFIG_LINE" -lt "$SHOW_LINE" ] || fail "pre-show configuration missing"
[ "$POST_CONFIG_LINE" -gt "$SHOW_LINE" ] || fail "hidden attached-window normalization missing"
DIRECT_CALLS="$(grep -R -h -E 'UiChrome\.show(Menu|Message|Record|Content|MultiChoice)Dialog\(' "$SRC" | wc -l | tr -d ' ')"
COMPAT_CALLS="$(grep -R -h -F 'UiChrome.alertBuilder(' "$SRC" | wc -l | tr -d ' ')"
CUSTOM_CALLS="$(expr "$DIRECT_CALLS" + "$COMPAT_CALLS")"
[ "$CUSTOM_CALLS" -ge 44 ] || fail "unexpected unified modal coverage: $CUSTOM_CALLS"
echo "PASS:"
echo "- WindowManager animation disabled"
echo "- whole attached decor hidden during Window normalization"
echo "- safe insets applied before reveal"
echo "- reveal waits for repeated stable geometry"
echo "- unified modal coverage: $CUSTOM_CALLS call sites"
