#!/usr/bin/env bash
set -euo pipefail
fail(){ echo "FAIL: $1" >&2; exit 1; }
UI="app/src/main/java/com/saney/ytmimporter/ui/UiChrome.kt"
SRC="app/src/main/java/com/saney/ytmimporter"
test -f "$UI" || fail "UiChrome.kt missing"
grep -A55 'fun configureWindow()' "$UI" | grep -q 'setWindowAnimations(0)' || fail "Window animation still enabled"
grep -A55 'fun configureWindow()' "$UI" | grep -q 'windowAnimations = 0' || fail "windowAnimations attr not zero"
grep -A20 'val holder =' "$UI" | grep -q 'Gravity.TOP' || fail "dialog not TOP anchored"
grep -A12 'val outer =' "$UI" | grep -q 'alpha = 0f' || fail "provisional content visible"
grep -q 'private fun customDialog' "$UI" || fail "dedicated Dialog factory missing"
grep -q 'dialog.setContentView' "$UI" || fail "direct Dialog content path missing"
if grep -q 'dialog.setOnShowListener' "$UI"; then fail "post-show geometry path returned"; fi
grep -A65 'setOnApplyWindowInsetsListener' "$UI" | grep -q 'ViewTreeObserver.OnPreDrawListener' || fail "pre-draw reveal gate missing"
CONFIG_LINE="$(grep -n '^[[:space:]]*configureWindow()$' "$UI" | tail -n 1 | cut -d: -f1)"
SHOW_LINE="$(grep -n '^[[:space:]]*dialog.show()$' "$UI" | tail -n 1 | cut -d: -f1)"
[ -n "$CONFIG_LINE" ] && [ -n "$SHOW_LINE" ] || fail "configure/show ordering markers missing"
[ "$CONFIG_LINE" -lt "$SHOW_LINE" ] || fail "window configured after show"
CUSTOM_CALLS="$(grep -R -h -E 'UiChrome\.show(Menu|Message|Record)Dialog\(' "$SRC" | wc -l | tr -d ' ')"
[ "$CUSTOM_CALLS" -ge 5 ] || fail "unexpected custom-dialog coverage: $CUSTOM_CALLS"
echo "PASS:"
echo "- custom Dialog WindowManager animation disabled"
echo "- window geometry is final before show()"
echo "- card remains TOP anchored"
echo "- provisional content stays hidden until safe insets"
echo "- reveal occurs on the first pre-draw after inset geometry is final"
echo "- shared fix covers $CUSTOM_CALLS custom dialog call sites"
